// Protocol Registry — AUTO-GENERATED by scripts/convert-protocols.py
// Do not edit manually. Run: python3 scripts/convert-protocols.py
//
// 37 protocols registered from 37 JSON files.

import type { ProtocolRegistryEntry, SynopticProtocol } from '$lib/types/synoptic';

export const PROTOCOL_REGISTRY: ProtocolRegistryEntry[] = [
  {
    file: 'adrenal_mar2023',
    label: 'Adrenal Gland (Mar 2023)',
    keywords: ['adrenal'],
  },
  {
    file: 'ampulla_nov2021',
    label: 'Ampulla of Vater (Nov 2021)',
    keywords: ['ampulla', 'vater'],
  },
  {
    file: 'anus_sep2023',
    label: 'Anus (Sep 2023)',
    keywords: ['anus', 'anal'],
  },
  {
    file: 'appendix_dec2022',
    label: 'Appendix (Dec 2022)',
    keywords: ['appendix', 'appendectomy'],
  },
  {
    file: 'bladder_jun2023',
    label: 'Urinary Bladder (Jun 2023)',
    keywords: ['bladder', 'cystectomy'],
  },
  {
    file: 'breastca_jun2024',
    label: 'Breast Carcinoma (Jun 2024)',
    keywords: ['breast', 'mastectomy', 'lumpectomy'],
  },
  {
    file: 'cervix_april2023',
    label: 'Cervix (Apr 2023)',
    keywords: ['cervix', 'cervical'],
  },
  {
    file: 'colon_rectum_resection_062024',
    label: 'Colon and Rectum Resection (Jun 2024)',
    keywords: ['colon', 'rectum', 'hemicolectomy', 'colectomy', 'sigmoid', 'cecum'],
  },
  {
    file: 'cxbx_mar2023',
    label: 'Cervix Biopsy (Mar 2023)',
    keywords: ['cervix biopsy', 'cervical biopsy'],
  },
  {
    file: 'dehb_jun2021',
    label: 'Extrahepatic Bile Duct (Jun 2021)',
    keywords: ['bile duct', 'extrahepatic'],
  },
  {
    file: 'endom_dec2023',
    label: 'Endometrium (Dec 2023)',
    keywords: ['endometrium', 'endometrial', 'uterus'],
  },
  {
    file: 'esophagus_jun2022',
    label: 'Esophagus (Jun 2022)',
    keywords: ['esophagus', 'esophageal', 'esophagectomy'],
  },
  {
    file: 'exgct_sep2023',
    label: 'Extragonadal Germ Cell Tumor (Sep 2023)',
    keywords: ['germ cell', 'extragonadal'],
  },
  {
    file: 'expan_nov2021',
    label: 'Exocrine Pancreas (Nov 2021)',
    keywords: ['pancreas', 'pancreatic', 'whipple'],
  },
  {
    file: 'gb_jun2021',
    label: 'Gallbladder (Jun 2021)',
    keywords: ['gallbladder', 'cholecystectomy'],
  },
  {
    file: 'gist_sep2023',
    label: 'GIST (Sep 2023)',
    keywords: ['gist', 'gastrointestinal stromal'],
  },
  {
    file: 'gtn_nov2021',
    label: 'Gestational Trophoblastic (Nov 2021)',
    keywords: ['gestational', 'trophoblastic', 'molar'],
  },
  {
    file: 'hcc_jun2022',
    label: 'Hepatocellular Carcinoma (Jun 2022)',
    keywords: ['hepatocellular', 'liver', 'hepatectomy'],
  },
  {
    file: 'ihb_jun2021',
    label: 'Intrahepatic Bile Duct (Jun 2021)',
    keywords: ['intrahepatic', 'cholangiocarcinoma'],
  },
  {
    file: 'kidneyres_jun2024',
    label: 'Kidney Resection (Jun 2024)',
    keywords: ['kidney', 'renal', 'nephrectomy'],
  },
  {
    file: 'larynx_jun2023',
    label: 'Larynx (Jun 2023)',
    keywords: ['larynx', 'laryngeal', 'laryngectomy', 'glottis'],
  },
  {
    file: 'lung_sep2022',
    label: 'Lung (Sep 2022)',
    keywords: ['lung', 'pulmonary', 'lobectomy', 'pneumonectomy'],
  },
  {
    file: 'mesothelioma_june2021',
    label: 'Mesothelioma (Jun 2021)',
    keywords: ['mesothelioma', 'pleural'],
  },
  {
    file: 'oral_jun2023',
    label: 'Oral Cavity / Oropharynx (Jun 2023)',
    keywords: ['oral', 'oropharynx', 'tongue', 'floor of mouth'],
  },
  {
    file: 'ovary_jun2024',
    label: 'Ovary / Fallopian Tube (Jun 2024)',
    keywords: ['ovary', 'ovarian', 'fallopian'],
  },
  {
    file: 'phb_jun2021',
    label: 'Perihilar Bile Duct (Jun 2021)',
    keywords: ['perihilar'],
  },
  {
    file: 'phyllodes_sep2022',
    label: 'Phyllodes Tumor (Sep 2022)',
    keywords: ['phyllodes'],
  },
  {
    file: 'proscore_sep2023',
    label: 'Prostate Scoring (Sep 2023)',
    keywords: ['prostate score', 'gleason'],
  },
  {
    file: 'prostaters_sep2023',
    label: 'Prostate Resection (Sep 2023)',
    keywords: ['prostatectomy', 'prostate, radical'],
  },
  {
    file: 'proturp_sep2023',
    label: 'Prostate TURP (Sep 2023)',
    keywords: ['turp', 'prostate, transurethral'],
  },
  {
    file: 'salivary_jun2023',
    label: 'Salivary Gland (Jun 2023)',
    keywords: ['salivary', 'parotid', 'submandibular'],
  },
  {
    file: 'stomach_mar2023',
    label: 'Stomach (Mar 2023)',
    keywords: ['stomach', 'gastric', 'gastrectomy'],
  },
  {
    file: 'testis_sep2023',
    label: 'Testis (Sep 2023)',
    keywords: ['testis', 'testicular', 'orchiectomy'],
  },
  {
    file: 'thymus_june2021',
    label: 'Thymus (Jun 2021)',
    keywords: ['thymus', 'thymoma', 'thymectomy'],
  },
  {
    file: 'thyroid_2023',
    label: 'Thyroid (2023)',
    keywords: ['thyroid', 'thyroidectomy', 'lobectomy'],
  },
  {
    file: 'uterus_sarc_mar2023',
    label: 'Uterine Sarcoma (Mar 2023)',
    keywords: ['uterine sarcoma', 'leiomyosarcoma'],
  },
  {
    file: 'vulva_jun2024',
    label: 'Vulva (Jun 2024)',
    keywords: ['vulva', 'vulvar', 'vulvectomy'],
  },
];

/**
 * Find the best-matching CAP protocol for a given specimen type.
 * Scores all entries and returns the one with the earliest keyword match
 * (position in the specimen string), preferring specificity over registry order.
 */
export function findProtocolForSpecimen(specimenType: string | null): ProtocolRegistryEntry | null {
  if (!specimenType) return null;

  const normalized = specimenType.toLowerCase();

  let bestEntry: ProtocolRegistryEntry | null = null;
  let bestScore = Infinity;

  for (const entry of PROTOCOL_REGISTRY) {
    for (const keyword of entry.keywords) {
      const pos = normalized.indexOf(keyword);
      if (pos !== -1 && pos < bestScore) {
        bestScore = pos;
        bestEntry = entry;
      }
    }
  }

  return bestEntry;
}

// Dynamic protocol loader — imports JSON at runtime
const protocolCache = new Map<string, SynopticProtocol>();

export async function loadProtocol(fileName: string): Promise<SynopticProtocol> {
  const cached = protocolCache.get(fileName);
  if (cached) return cached;

  // Vite dynamic import for JSON files in the data directory
  const modules = import.meta.glob('./*.json');
  const importFn = modules[`./${fileName}.json`];

  if (!importFn) {
    throw new Error(`Protocol file not found: ${fileName}.json`);
  }

  const module = await importFn() as { default: SynopticProtocol };
  const protocol = module.default;
  protocolCache.set(fileName, protocol);
  return protocol;
}
